name: Dart

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - uses: subosito/flutter-action@v1

      - name: Install dependencies
        run: flutter pub get
        
      - uses: actions/checkout@v2
      - name: Get flutter version
        id: get_flutter_version
        uses: its404/get-flutter-version@v1.0.0
        
      - name: Output flutter version
        run: echo 'version_number:' ${{ steps.get_flutter_version.outputs.version_number }} ' build_number:' ${{ steps.get_flutter_version.outputs.build_number }}

      # Uncomment this step to verify the use of 'dart format' on each commit.
      # - name: Verify formatting
      #   run: dart format --output=none --set-exit-if-changed .

      # Consider passing '--fatal-infos' for slightly stricter analysis.
      # - name: Analyze project source
      #   run: dart analyze

      # Your project will need to have tests in test/ and a dependency on
      # package:test for this step to succeed. Note that Flutter projects will
      # want to change this to 'flutter test'.
      # - name: Run tests
      #   run: dart test

#       - name: Dart and Flutter Package Publisher
#         uses: k-paxian/dart-package-publisher@v1.3
#         with:
#           accessToken: ${{ secrets.OAUTH_ACCESS_TOKEN }}
#           refreshToken: ${{ secrets.OAUTH_REFRESH_TOKEN }}
#           dryRunOnly: true
